# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zyFiFjj9jw90qzxON9JqgrDCWeNPEFeg
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def VaR(r, confidence, principal=1):
    var_percentile = np.percentile(r, (1 - confidence) * 100)
    return principal * abs(var_percentile)

np.random.seed(42)
returns = np.random.normal(0.001, 0.02, 100000)

confidence_level = 0.95
var_value = VaR(returns, confidence_level, principal=1000000)

plt.figure(figsize=(10, 5))
plt.hist(returns, bins=50, alpha=0.75, color='blue', edgecolor='black', density=True)
plt.axvline(x=-var_value/1000000, color='red', linestyle='dashed', linewidth=2, label=f'VaR at {confidence_level*100}%: ${var_value:,.2f}')
plt.title("Histogram of Simulated Stock Returns with VaR")
plt.xlabel("Returns")
plt.ylabel("Frequency")
plt.legend()
plt.show()



print(f"Value at Risk (VaR) at {confidence_level*100}% confidence: ${var_value:,.2f}")