# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157M7QpneS4ILNu3LJQ2Tds9Vj3Ct_Oka
"""

import yfinance as yf
import pandas as pd

def get_stock_data(symbol):
    """
    Fetches stock data for a given symbol from Yahoo Finance and returns available columns.
    Sorted to show the most recent data at the top.
    """
    data = yf.download(symbol)

    # Print available columns while no Adjusted colum
    print(f"Available columns for {symbol}: {data.columns}")

    return data[['Open', 'High', 'Low', 'Close', 'Volume']].iloc[::-1]  # Reverse order from latest to oldest

def get_returns(pricevec):
    """
    Computes daily returns from a series of stock prices.
    """
    n = len(pricevec)
    ratiovec = pricevec[1:n] / pricevec[:n-1]
    returns = ratiovec - 1  # (price_t / price_t-1) - 1
    return returns

# Example usage
if __name__ == "__main__":
    symbol = 'GS'  # Goldman Sachs
    stock_data = get_stock_data(symbol).head(100)  # latest 100 records

    print("Stock Data (Latest 100 Entries):")
    print(stock_data)